### PR TITLE
Completed Developer Recruitment Test 

### PR DESCRIPTION
**Pull request by hefazi**

### CODE REVIEW

**Review by yeganemehr — CHANGES_REQUESTED** [review]
Hi Mohammad
Thank you for participating in the challenge.
I ran the tests and 9 of 39 tests failed.
PhpUnit logs attached.
[phpunit.log](https://github.com/dnj/developer-recruitment/files/10298557/phpunit.log)



Travel Event (Tests\Unit\Models\TravelEvent)

    ✓ Relations

Travel (Tests\Unit\Models\Travel)

    ✓ Relations

Auth Controller (Tests\Feature\AuthController)

    ❌ Register
    ✓ User

Driver Controller (Tests\Feature\DriverController)

    ✓ Signup
    ✓ Update

Travel Controller (Tests\Feature\TravelController)

    ❌ Store
    ✓ Store with bad positions
    ✓ Store when have active travel
    ❌ Cancel searching for driver as passenger
    ✓ Cancel finished travel
    ✓ Cancel onboard passenger
    ❌ Cancel arrived car
    ✓ View
    ❌ Passenger on board
    ✓ Passenger on board as passenger
    ✓ Passenger on board when car is not arrived
    ✓ Passenger on board finished travel
    ❌ Done
    ✓ Done as passenger
    ✓ Done when spots skipped
    ❌ Take
    ✓ Take cancelled travel
    ✓ Take with active travel

Travel Spot Controller (Tests\Feature\TravelSpotController)

    ✓ Arrived
    ✓ Arrived as passenger
    ✓ Arrived not running travel
    ✓ Arrived when already arrived
    ❌ Store
    ✓ Store as driver
    ❌ Store out of range
    ✓ Store arrived
    ✓ Store not running travel
    ✓ Destroy
    ✓ Destroy not running travel
    ✓ Destroy as driver
    ✓ Destroy arrived
    ✓ Destroy origin
    ✓ Destroy last spot

**Comment by hefazi** [comment]
Hello Amir (@yeganemehr )
I used Eloquent to connect to the database - so I had to change the value of the fillable parameter in the models.
Please update the models in addition to the controllers for testing.

Thankful

**Comment by yeganemehr** [comment]
Challenge is to write your code in a way that pass the tests.

**Comment by hefazi** [comment]
The tests are passed.

**Pull request closed without merging**
