### PR TITLE
Finish the project

### PR DESCRIPTION
**Pull request by amiranbari**
I made a mistake and that is :

commit the changes in my directory not in the root of the project.

This is the reason why you cannot see my commits.

I hope you accept my apology

### CODE REVIEW

**Review by yeganemehr — CHANGES_REQUESTED** [review]
Hi Amir
Thank you for participating in the challenge.
I ran the tests and 17 of 39 tests failed.
You can download phpunit logs: 
[phpunit.log](https://github.com/dnj/developer-recruitment/files/10313720/phpunit.log)


Travel Event (Tests\Unit\Models\TravelEvent)

    ✓ Relations

Travel (Tests\Unit\Models\Travel)

    ✓ Relations

Auth Controller (Tests\Feature\AuthController)

    ✓ Register
    ✓ User

Driver Controller (Tests\Feature\DriverController)

    ✓ Signup
    ✓ Update

Travel Controller (Tests\Feature\TravelController)

    ✓ Store
    ✓ Store with bad positions
    ✓ Store when have active travel
    ❌ Cancel searching for driver as passenger
    ✓ Cancel finished travel
    ✓ Cancel onboard passenger
    ❌ Cancel arrived car
    ❌ View
    ❌ Passenger on board
    ✓ Passenger on board as passenger
    ✓ Passenger on board when car is not arrived
    ✓ Passenger on board finished travel
    ❌ Done
    ✓ Done as passenger
    ✓ Done when spots skipped
    ✓ Take
    ✓ Take cancelled travel
    ✓ Take with active travel

Travel Spot Controller (Tests\Feature\TravelSpotController)

    ❌ Arrived
    ❌ Arrived as passenger
    ❌ Arrived not running travel
    ❌ Arrived when already arrived
    ❌ Store
    ✓ Store as driver
    ❌ Store out of range
    ✓ Store arrived
    ❌ Store not running travel
    ❌ Destroy
    ❌ Destroy not running travel
    ✓ Destroy as driver
    ❌ Destroy arrived
    ❌ Destroy origin
    ❌ Destroy last spot

**Comment by amiranbari** [comment]
I wrote the controller only according to the test and did not test it myself.
Of course, it is because I did not have enough time to run the tests.
And the total time I took was 2 hours

**Comment by yeganemehr** [comment]
I closed this due to inactivity.

**Comment by amiranbari** [comment]
Thank you very much, when will you let me know the result?

**Pull request closed without merging**
