### PR TITLE
Challenge 4 - elmi-elmi

### PR DESCRIPTION
**Pull request by elmi-elmi**
Challenge completed.

### CODE REVIEW

**Review by yeganemehr — CHANGES_REQUESTED** [review]
Hi Alireza
Thank you for participating in the challenge.
It's your implementation or something went wrong?
Screen Shot 2022-12-24 at 16 03 39

**Comment by elmi-elmi** [comment]
Screenshot 2022-12-24 164441
Hi Amir,
It appears that something went wrong, here is my implementation.
[image: image.png]

**Comment by yeganemehr** [comment]
Your attachment is not showing up if you send it by email.
Please deploy your code somewhere and make sure it's looking good.

**Comment by elmi-elmi** [comment]
> Hi Alireza Thank you for participating in the challenge. It's your implementation or something went wrong? Screen Shot 2022-12-24 at 16 03 39

Screenshot 2022-12-24 164441

**Comment by elmi-elmi** [comment]
Here is my implementation.

**Comment by yeganemehr** [comment]
okay, it's pretty much the same.

**Comment by yeganemehr** [comment]
I merged it.

Thank you for all of the time you have put into the interview process.
HR'll call you soon.

**Comment by elmi-elmi** [comment]
I did the major part, dear Amir. There was no time for me. It's not my best
work.
Thank you.

**Pull request merged**
